# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
    
  - name: Publications
    url: '/publication'
    weight: 20
    target: "_blank"
  - name: CV
    url: 'https://docs.google.com/document/d/1df2KVh0iR_Kbvc2GMum00jBleyb5Ia8-bUO0Z1IGd54/edit?usp=sharing'
    weight: 30
    target: '_blank'


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
